### ISSUE TITLE
Error when installing requirements.txt

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/sqlBRAT#86] opened 2020-08-14 00:42 UTC
I've tried installing all of the libraries in requirements.txt so I can run raster_vat.py. However, I keep running into errors, and I could use some help figuring it out. Installing libraries is not my strong suit. 

It seems that GDAL is having trouble installing:

```
Collecting rasterio>=1.0.23
  Using cached rasterio-1.1.5.tar.gz (2.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\a02079569\appdata\local\programs\python\python38-32\python.exe' 'c:\users\a02079569\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\TEMP\tmpdp8508t6'
       cwd: C:\TEMP\pip-install-crol0lzz\rasterio
  Complete output (2 lines):
  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\a02079569\appdata\local\programs\python\python38-32\python.exe' 'c:\users\a02079569\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel
 'C:\TEMP\tmpdp8508t6' Check the logs for full command output.
```

Any help would be appreciated.

**Comment by MattReimer** [comment] 2020-08-17 15:58
Hey Tyler,

Everyone has trouble with this stuff. That's because package management across platforms in python sucks.

First off you **must** use python3 for this. I assume you are but it's worth mentioning.

I highly recommend you use a virtualenv for your deployments. This allows you to keep all your packages separated and use different versions of packages and even python itself across different projects.

If you've ticked these two boxes the problem is likely that you don't have gdal installed

Go and find a link that suits your machine:

- `gdal`: Versions >3.1: <https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal>
    - `GDAL‑3.1.2‑cp38‑cp38‑win_amd64.whl`

You need at least GDAL 3.1 and you need your python version `cp38 === python 3.8`, operating system and architecture to match what you're using

Then, once you've installed the wheel file:

```
c:\>pip install c:\some\path\to\wherever\GDAL‑3.1.2‑cp38‑cp38‑win_amd64.whl
```

You should be able to re-run the `requirements.txt` installation and it should all work.

Get in touch if you're struggling. I'm sure we can figure this out quickly.

**Comment by MattReimer** [comment] 2020-08-25 17:43
I'm closing this for now.  Please re-open if you're still having trouble.

**Closed by MattReimer** 2020-08-25 17:43 UTC
Labels: help wanted
