### ISSUE TITLE
Management Values are NULL in some watersheds

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/sqlBRAT#59] opened 2020-07-01 23:33 UTC
In HUC 14050001, all management values are missing. This means they can't be symbolized, and affects other estimates down the line.

![image](https://user-images.githubusercontent.com/27084463/86300714-5fe6c000-bbc9-11ea-94cf-f9d24008bbea.png)
![image](https://user-images.githubusercontent.com/27084463/86300719-6412dd80-bbc9-11ea-866c-a1553e89f6d6.png)

**Comment by philipbaileynar** [comment] 2020-08-25 18:10
This was caused by a long chain of problems. I think it all started with the historic vegetation raster not covering the extent of this HUC. THis caused invalid historical capacity, which then broke many of the management/conservation logic rules.

The historic veg raster has been extended by @tyler1218hatch to cover the US states that we will run most often. We also updated the logic to write -1 when values are invalid, so it should be easier to spot problems like this going forward.

Closing this issue.

**Closed by philipbaileynar** 2020-08-25 18:10 UTC
Labels: bug
