### ISSUE TITLE
BRAT Validation Issues

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/sqlBRAT#36] opened 2020-05-21 20:28 UTC
Based on a call we had with @mhallerud and @wally-mac 

### Possible unit problems in the equations

```
DRNAREA=sqMiles
ELEV=ft (5693)
FOREST=% (17.31)
PRECIP=in (21.77)

QLow
0.0247 * ((DRNAREA/0.3861021585424458)**1.05) * ((ELEV/3.28084)**-3.86) * (FOREST**-0.947) * ((PRECIP/0.0393701)**3.99)

Q2
0.00557 * ((DRNAREA/0.3861021585424458)**0.754) * ((PRECIP/0.0393701)**2.34)
```

here's an excerpt from the DB

```csv
PRECIP	PRECIP,PRECPRIS10	536.4481810897436
ELEV	ELEV	1735.325498590117
MINELEV	MINELEV,MINBELEV	1334.19677734375
RR	RR	1707.66357421875
FOREST	FOREST	11.979218556596658
SLOP30_30M	SLOP30_30M	4.073632316368693
MEANSLOPE	MEANSLOPE	10.095673577064435

```

Here's the code that drives this:
https://github.com/Riverscapes/sqlBRAT/blob/master/hydrology.py#L91-L96

Maggie sent some reference images.

<img width="732" alt="Screen Shot 2020-05-21 at 1 25 03 PM" src="https://user-images.githubusercontent.com/1063391/82602800-7d565200-9b66-11ea-9b65-82f7130ee1b6.png">
<img width="732" alt="Screen Shot 2020-05-21 at 1 25 23 PM" src="https://user-images.githubusercontent.com/1063391/82602838-89daaa80-9b66-11ea-8b12-2ac7b759bb5d.png">
<img width="1106" alt="Screen Shot 2020-05-21 at 1 25 41 PM" src="https://user-images.githubusercontent.com/1063391/82602884-94953f80-9b66-11ea-8484-b31a227fc23f.png">
<img width="762" alt="Screen Shot 2020-05-21 at 1 25 59 PM" src="https://user-images.githubusercontent.com/1063391/82602910-9d861100-9b66-11ea-9c0c-43f8f55c6141.png">

**Comment by philipbaileynar** [comment] 2020-05-21 22:50
This is the equation that we are using for low flow in Station Creek (16010202):

```python
0.0247 * ((DRNAREA/0.3861021585424458)**1.05) * ((ELEV/3.28084)**-3.86) * (FOREST**-0.947) * ((PRECIP/0.0393701)**3.99)
```

Earlier today we confirmed that the terms use the following units:

* DRNAREA in square miles
* ELEV in feet
* FOREST as a percent
* PRECIP in inches

My ultimate question for @mhallerud is whether the value 0.3861021585424458 is from the cited USGS publication or whether this is an attempt to convert from drainage area values in our data stored in square kilometres to the necessary square miles for the equation to work?

1 square kilometre = 0.386102 square miles

So shouldn't this term be:

```python
DRNAREA * 0.386102
```

I think it's a good idea if the equations used by the code are taken directly from the literature and that we keep all conversion factors elsewhere (I propose the database).

**Comment by mhallerud** [comment] 2020-05-21 23:38
@philipbaileynar Not sure why there are extra digits, but yes the purpose of that value is converting from square kilometers to square miles.

**Comment by philipbaileynar** [comment] 2020-05-22 00:40
@mhallerud was the conversion factor in the literature? Or was it added by ETAL to convert from our source data?

**Comment by mhallerud** [comment] 2020-05-22 00:54
@philipbaileynar It was added by us, the literature just specified that drainage area was in square miles.

**Comment by philipbaileynar** [comment] 2020-05-28 15:35
## Hydrology
The problems with hydrology were caused by several unit conversion errors. I have simplified this greatly and am now getting comparable discharge and stream power values with pyBRAT.

![high_stream_power](https://user-images.githubusercontent.com/8645379/83161740-affbcf80-a0bd-11ea-931d-a8bc10df3a16.png)

## Vegetation
sqlBRAT was consistently under reporting the vegetation suitability. This was caused by an SQL query error that was double accounting the area of each buffer (because it was combining both existing and historical buffers during each query). So the proportion of any vegetation type was diminished because it was a fraction of twice the area. This is fixed.

![existing_veg_suitability](https://user-images.githubusercontent.com/8645379/83161770-b9853780-a0bd-11ea-9802-32ef20338f56.png)

## Dam Capacity

The dam capacitty looks much more comparible. sqlBRAT has lower values in the central valley. This requires further investigation, but I am really pleased that the most egregious errors are fixed.

![existing_dam_capacity](https://user-images.githubusercontent.com/8645379/83161964-f5b89800-a0bd-11ea-95b1-a812bdcd0f57.png)

Shout out to @wally-mac @Cashe93 @joewheaton @MattReimer so they see this important update.

**Comment by joewheaton** [comment] 2020-05-28 16:42
Really nice work all.... This is getting closer. At a cursory glance, almost everything in sqlBRAT that is red, which is orange in pyBRAT are canals. Any thoughts?

**Comment by wally-mac** [comment] 2020-05-28 17:09
@philipbaileynar wow, this looks so much better! Nice work troubleshooting the hydrology and the veg. @philipbaileynar @joewheaton  Do you guys have suggestions on how to further investigate the differences especially in the "central" portion of the watershed. Is this sqlBRAT run now available in the warehouse? @philipbaileynar @joewheaton If you guys think it's a good next step @Cashe93 let's interrogate these differences in outputs together and see if we can figure out what's driving the changes. Very impressive work. Big relief that we are making such great headway.

**Comment by philipbaileynar** [comment] 2020-05-28 17:11
@wally-mac yes this latest version of middle bear is in the Anabranch warehouse. 

I welcome any investigation that @Cashe93 can perform that sheds light. 

I'm curious about @joewheaton "canal" comment and will investigate also.

**Comment by Cashe93** [comment] 2020-05-28 17:23
Sounds good @wally-mac. Nice work @philipbaileynar!

**Comment by philipbaileynar** [comment] 2020-05-28 17:25
Here is a video demonstrating the new BRAT report that is produced with every sqlBRAT run. The goal is to make the inner workings and results of sqlBRAT more transparent. I know some folks are not yet comfortable with SQL databases, so this report gets important results into an easily accessible HTML format that anyone can view in a web browser to investigate a BRAT run.

https://youtu.be/aLsDlcYW8CM

The report code is unbelievably simple. We intend to extend it to include the electivity indices and other valuable summary information. We also hope to write similar reports for riverscapes context and VBET projects. And we encourage all model owners to consider doing the same for their models too.

**Comment by wally-mac** [comment] 2020-05-28 17:54
@philipbaileynar Thank you for generating the BRAT report. I watched the video and found the report very useful. I agree, I think a report like this would be great to have for each of our tools. Thank you!

**Comment by joewheaton** [comment] 2020-05-29 01:04
More importantly, what @philipbaileynar just made is easy enough that @tyler1218hatch or @Cashe93 could implement. Really powerful. It needs us to really think about exactly what we want to show and graph, but super cool. @kbartelt may like too.

**Comment by philipbaileynar** [comment] 2020-06-01 02:08
Closing this issue now that the core task of getting sqlBRAT to produce comparable results to pyBRAT. Any subsequent validation issues should use a new issue. Refer back to this issue if relevant.

**Closed by philipbaileynar** 2020-06-01 02:08 UTC
Labels: bug
