### ISSUE TITLE
Suitability Raster has all values as 0

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/sqlBRAT#61] opened 2020-07-01 23:37 UTC
In HUC 14050002, the only suitability values are zero. This could be because of the issue mentioned in #60, but it  could also be something else.
![image](https://user-images.githubusercontent.com/27084463/86300880-e69b9d00-bbc9-11ea-9140-d7596a3d9857.png)

**Comment by philipbaileynar** [comment] 2020-07-17 03:26
This is now fixed.

The line down the middle was caused by an out of date historical raster problem.

You can ignore that the image below is all grey. This screenshot was taken in my ArcGIS 10.4 which can use the layer files for rasters created on newer versions even though they are saved as 10.4.

<img width="1097" alt="Screen Shot 2020-07-16 at 8 21 44 PM" src="https://user-images.githubusercontent.com/8645379/87745129-fa3a2c80-c7a1-11ea-89ab-4f60771709c3.png">

**Closed by philipbaileynar** 2020-07-17 03:26 UTC
